### ISSUE TITLE
HDR image generation workflow description

### ISSUE THREAD

**Issue by adulbrich** [radiantlab/HDRICalibrationTool#10]
Description of the "sitemap" or what the app should cover for the HDR image generation workflow/process, this might include steps, data, ...

Previous pipeline: https://github.com/clopierson/radiance_pipeline

Original tutorial paper with all commands: https://www.tandfonline.com/doi/full/10.1080/15502724.2019.1684319

For each step:
1. Write down the command line command
2. List expected inputs/parameters (data)
3. List expected output

The goal is to have a list of all inputs/parameters and their format so that we can save these on the frontend and pass it down to the pipeline.

**Comment by shantimorrell** [comment]
HDR image generation workflow description available here: [Workflow Description](https://docs.google.com/document/d/1tT4zebzbG_tH8EO-0-ZmEQjnrIsFu-yoXjZ5pYDEnx0/edit#heading=h.ukmubzu9i908)

The overview contains a more brief list of commands and inputs/outputs. There is a section below for more detailed information about each command and explanation of what that step entails.

I wasn't sure how best to represent it, so please let me know if it would be more helpful to have the information presented in a different way!

**Comment by shantimorrell** [comment]
Updated commands and re-ordered them to reflect tutorial version (which should be considered the correct version) rather than existing radiance pipeline version, as there were some conflicts
