### ISSUE TITLE
Port v0 app to Figma

### ISSUE THREAD

**Issue by adulbrich** [radiantlab/HDRICalibrationTool#13]
Run the existing app and identify the different UI elements.

In the Figma project, recreate the wireframes for future iteration.

Feel free to already make the UI port more usable/pleasing to look at.

We'll iterate on the design from there, but at least we have the base elements (required input fields, etc.)

**Comment by shantimorrell** [comment]
I've created a few very rough design ideas in Figma (Figma team was shared in Discord previously by Alex). More needs to be done, but hopefully there's enough variety there we can at least start thinking about what aspects of the different ideas we like or don't like, and let that lead future iterations.
