### ISSUE TITLE
Redesign the selection and preview of LDR images

### ISSUE THREAD

**Issue by adulbrich** [radiantlab/HDRICalibrationTool#14]
The user can select images on their local filesystem. The images are then listed in the app to be previewed and can be removed from the list.

Open questions:
- Should we list paths or image names (or let the user choose)?
- Should we be able to add more images or simply overwrite current selection?
- What kind of information/details about images would be useful to list next to the image path/name, if any? (resolution, exposure, etc. check the rest of the process)

**Comment by stack461** [comment]
I included the image names on issue19, this was just as easy as including a div containing the image name. The way I have it set up is to have images be able to be added and deleted without losing their selection. This seems intuitive. I think for now the name and type is what is necessary especially if its just a selection. A file description could possibly added in a different part of the application.
