### ISSUE TITLE
Initialize Starlight docs

### ISSUE THREAD

**Issue by adulbrich** [radiantlab/HDRICalibrationTool#23]
1. In the fork, create new branch, and create a new directory called `docs`
2. Initialize the documentation with Starlight by following tutorial here: https://starlight.astro.build/getting-started/
3. Run documentation site and make sure it works
4. Open PR

**Comment by shantimorrell** [comment]
Pull request in forked repo created here: [https://github.com/zwall-bp/HDRICalibrationTool-Capstone/pull/1](https://github.com/zwall-bp/HDRICalibrationTool-Capstone/pull/1)

Starlight docs initialized in ./src-docs. PR can be merged once the Tauri app has been initialized in the forked repo (issue #18).
