### ISSUE TITLE
Find a way to check whether hdrgen command succeeds/fails

### ISSUE THREAD

**Issue by adulbrich** [radiantlab/HDRICalibrationTool#64]
by @shantimorrell 

App currently assumes this command succeeds, I believe because I was having issues checking if the result was successful previously, and hadn't yet found a way to do this.

Investigate if we can prevent the next step of the pipeline if the hdrgen step fails.

**Comment by adulbrich** [comment]
Could we save the result from the command and check it?

**Comment by shantimorrell** [comment]
Checked the status slightly differently than the other commands. When hdrgen fails because _output1.hdr_ file exists, the pipeline will now terminate.

Fix is in branch _batch_fixes_, will open a pr later
