### ISSUE TITLE
Error check for directory inputs

### ISSUE THREAD

**Issue by adulbrich** [radiantlab/HDRICalibrationTool#65]
by @shantimorrell 

At least for macos, radiance, hdrgen, output, and temp directories must currently start and end with `/`. Otherwise, for example, it outputs `tmpoutput_.hdr` when the input is `/tmp`

**Comment by adulbrich** [comment]
Could we use regex on save to add/remove the necessary `/` or other characters?

**Comment by shantimorrell** [comment]
This should now be working for the trailing slash for all four paths on branch _batch_processing_. Still need the beginning `/` for now, at least if on macOS. Can investigate that more a little later.
